[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "forge-cache"

remappings = [
    "@openzeppelin/contracts=lib/@openzeppelin/contracts/",
    "OAO/=lib/OAO/"
]

# Enable Optimizer and IR-based Compilation to avoid "Stack too deep" errors
optimizer = true
optimizer_runs = 200
via_ir = true

# Gas Reports for better optimization insights
gas_reports = ["*"]

# Increase stack depth limit if needed
solc_version = "0.8.23"
bytecode_size_limit = 24576
